# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6fde8db911797ece8b4a9af865bb9e19f2ed91c11109ae909e0b5b9553aabfc3e902cb4801c0499c30ea4cd0901753318b0ae8e5b71a10a58af54730555b4fc

test:
  secret_key_base: a1ff53ee312b05330fde6f0b4cbd016ddabb70725c99df03179d129aa77b1915c2cb53684fe54a552dfe1a0954388989231b51a31acb90e87c89686ca018dba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
